"""Initialize db

Revision ID: 81cae891e773
Revises: 
Create Date: 2022-10-12 18:27:05.806692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cae891e773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_festival_id'), 'festival', ['id'], unique=False)
    op.create_index(op.f('ix_festival_name'), 'festival', ['name'], unique=True)
    op.create_table('user',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=False)
    op.create_table('festivalattendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'user_id', name='attendee_single_status_constraint')
    )
    op.create_index(op.f('ix_festivalattendee_festival_id'), 'festivalattendee', ['festival_id'], unique=False)
    op.create_index(op.f('ix_festivalattendee_id'), 'festivalattendee', ['id'], unique=False)
    op.create_index(op.f('ix_festivalattendee_user_id'), 'festivalattendee', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_festivalattendee_user_id'), table_name='festivalattendee')
    op.drop_index(op.f('ix_festivalattendee_id'), table_name='festivalattendee')
    op.drop_index(op.f('ix_festivalattendee_festival_id'), table_name='festivalattendee')
    op.drop_table('festivalattendee')
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_festival_name'), table_name='festival')
    op.drop_index(op.f('ix_festival_id'), table_name='festival')
    op.drop_table('festival')
    # ### end Alembic commands ###
